### ISSUE TITLE
Error creating snapshot for disk with drive letter and path mount

### ISSUE THREAD

**Issue by cristihcd** [pescuma/go-fs-snapshot#2]
Hello,

I have a server which has a disk with both a drive letter (`H:`) and a path mount (`C:\Mount\D31`). 
After enabling VSS on the path, I get the following error:
```
kopia.exe snapshot create H:\VM
Snapshotting user@svr:H:\VM ...
Created filesystem snapshot for 'H:\, ount\D31\' using provider 'Microsoft Software Shadow Copy provider 1.0' and mapped to '\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy2\'
ERROR upload error: can't create snapshot local fs entry: unable to determine entry type: CreateFile \\?\GLOBALROOT\VM: The system cannot find the file specified.
```
Notice the path: `H:\, ount\D31\`

If I remove the path mount (`C:\Mount\D31`), the VSS snapshot succeeds:
```
Snapshotting user@svr:H:\VM ...
Created filesystem snapshot for 'H:\' using provider 'Microsoft Software Shadow Copy provider 1.0' and mapped to '\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy5\'
```

Thanks for looking into this.

**Comment by pescuma** [comment]
Can you test again, please? It should be fixed now.

**Comment by cristihcd** [comment]
Hello. Sorry for the late comment, I have just now had the time to test it. 
It works ok now.
Thank you.
