### ISSUE TITLE
fs_snapshot enable test should also check for scheduled task presence

### ISSUE THREAD

**Issue by cristihcd** [pescuma/go-fs-snapshot#3]
Hello,

Another small oversight I think :)

I deleted the scheduled task folder and ran test. It did not check for scheduled task presence.

Thanks for looking into this.

```
C:\Windows\system32>fs_snapshot enable test
Current user ([...]\admin) can create snapshots.

C:\Windows\system32>fs_snapshot enable for current-user
User [...]\admin already has SeBackupPrivilege

User [...]\admin already has SeBatchLogonRight

Creating scheduled task "\fs_snapshot\server start ([...]_admin)"
```

**Comment by pescuma** [comment]
I think it may be working as expected. The `fs_snapshot enable test` does not test exactly if the task is created, but if the current console can create the snapshot. So, it first tries to create it directly, then it tries to use the task. If it is run as administrator than the first check should work and the task is not tested. Try to run it as a normal user and it should complain.

**Comment by cristihcd** [comment]
You are right :)
Thank you.
